apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: valkey-pod-reader-binding
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: valkey-pod-reader
subjects:
- kind: ServiceAccount
  name: valkey-pod
  namespace: system
